CREATE TABLE  CONTACT  
   (	
     CT_ID  NUMERIC(19,0) NOT NULL, 
	 ADDRESS  VARCHAR(255), 
	 EMAIL  VARCHAR(255), 
	 PHONE  VARCHAR(255), 
	 PRIMARY KEY ( CT_ID )
    );
INSERT INTO  CONTACT  VALUES (1,'Ankara', 'sertacguler1@gmail.com', '05554443322');
   

    CREATE TABLE CUSTOMER  
   (	
    ID  NUMERIC(19,0) NOT NULL, 
	 ADDRESS  VARCHAR(255), 
	 EMAIL  VARCHAR(255), 
	 NAME  VARCHAR(255), 
	 PASSWORD  VARCHAR(255), 
	 PHONE  VARCHAR(255), 
	 SURNAME  VARCHAR(255), 
	 PRIMARY KEY ( ID )
    );
	INSERT INTO  CUSTOMER  VALUES (1, 'Ankara', 'sertacguler1@gmail.com', 'sertac', '$2a$10$4j3s7Br1.Kg1ihtVfAV/y.VliPCRBAYBdkTQH7WSn3mhC0ocqHxeq', '123456789', 'guler');
	INSERT INTO  CUSTOMER  VALUES (2, 'Istanbul', 'burak', 'burak@gmail.com', '$2a$10$4j3s7Br1.Kg1ihtVfAV/y.VliPCRBAYBdkTQH7WSn3mhC0ocqHxeq', '123456789', 'yılmaz');


	CREATE TABLE  EMPLOYEE  
   (	
     EMP_ID  NUMERIC(19,0) NOT NULL, 
	 NAME  VARCHAR(255), 
	 PASSWORD  VARCHAR(255), 
	 SURNAME  VARCHAR(255), 
	 USERNAME  VARCHAR(255), 
	 PRIMARY KEY ( EMP_ID )
    );
	INSERT INTO  EMPLOYEE  VALUES (1, 'mesut', '$2a$10$Ojm9B05Bt3uyX1.la7d80.JOteZQ7IUUNuiGpF4UNA//bAuJaCcbC', 'can', 'mesutcan');
   

    CREATE TABLE  MEAL  
   (	
     CODE  VARCHAR(255) NOT NULL, 
	 DETAIL  VARCHAR(255), 
	 NAME  VARCHAR(255), 
	 PHOTO  VARCHAR(255), 
	 PRICE  NUMERIC(19,0), 
	 EMP_ID  NUMERIC(19,0), 
	 CREATION_DATE  TIMESTAMP (6), 
	 CAMPAIGN BOOLEAN NOT NULL, 
	 PRIMARY KEY ( CODE ), 
	 CONSTRAINT FKMDYICEV5YBSHUIDC12K38CAJ7 FOREIGN KEY ( EMP_ID ) REFERENCES EMPLOYEE ( EMP_ID )
    );
	INSERT INTO  MEAL  VALUES ('CRB1', 'Mis gibi', 'Mercimek', 'https://im.haberturk.com/2019/09/13/ver1568794591/2521922_810x458.jpg', 5, 1, '2019-11-07 03:00:00', TRUE);
	INSERT INTO  MEAL  VALUES ('KVR1', 'Harika', 'Kavurma', 'https://i4.hurimg.com/i/hurriyet/75/750x422/5d4fca332269a20f5c723a58.jpg', 25, 1, '2019-11-07 03:00:00', FALSE);
	INSERT INTO  MEAL  VALUES ('MNT1', 'İçi dolu dolu', 'Mantı', 'https://lezzet.blob.core.windows.net/images-xxlarge-recipe/kayseri_mantisi-51ae051e-edd3-48f1-a54b-7f728dc93461.jpg', 12, 1,'2019-11-07 03:00:00', TRUE);


   CREATE TABLE  CART  
   (	
    CART_ID  NUMERIC(19,0) NOT NULL , 
	 STATUS  BOOLEAN NOT NULL , 
	 TOTAL_PRICE  VARCHAR(255), 
	 CUSTOMER_ID  NUMERIC(19,0) NOT NULL , 
	 PRIMARY KEY ( CART_ID ),
	 CONSTRAINT  FKDEBWVAD6PP1EKIQY5JTIXQBAJ  FOREIGN KEY ( CUSTOMER_ID ) REFERENCES  CUSTOMER  ( ID ) 
    );
    
     CREATE TABLE  CART_MEAL  
   (	
	 CART_ID  NUMERIC(19,0) NOT NULL , 
	 CODE  VARCHAR(255) NOT NULL , 
	CONSTRAINT  FKAKX1SJ4PEAIPH90OSHG5W1PO1  FOREIGN KEY ( CODE ) REFERENCES  MEAL  ( CODE ) , 
	CONSTRAINT  FK3PTI8YR2T6LHGPLM6KJB6SAOE  FOREIGN KEY ( CART_ID ) REFERENCES  CART  ( CART_ID ) 
   );
   
   
	CREATE TABLE  ROLE  
   (	
     ROLE_ID  NUMERIC(19,0) NOT NULL , 
	 EXPLANATION  VARCHAR(255), 
	 NAME  VARCHAR(255), 
	 PRIMARY KEY ( ROLE_ID )
	);
	INSERT INTO  ROLE  VALUES (1, 'Owner of the restaurant', 'RESTAURANT_OWNER');


	 CREATE TABLE  EMPLOYEE_ROLE  
   (	 EMP_ID  NUMERIC NOT NULL , 
	 ROLE_ID  NUMERIC NOT NULL , 
	 ACTIVE  BOOLEAN, 
	 SINCE  TIMESTAMP (6) NOT NULL ,
	 CONSTRAINT  EMPLOYEE_ROLE_FK1  FOREIGN KEY ( EMP_ID ) REFERENCES  EMPLOYEE  ( EMP_ID ) , 
	 CONSTRAINT  EMPLOYEE_ROLE_FK2  FOREIGN KEY ( ROLE_ID ) REFERENCES  ROLE  ( ROLE_ID ) 
   );
   INSERT INTO  EMPLOYEE_ROLE  VALUES (1, 1, 1, '2019-11-07 03:00:00');
   

 CREATE TABLE DELIVERY (
ID NUMERIC NOT null,
DELIVERY_STATUS BOOLEAN NOT NULL,
TIP VARCHAR(255),
DELIVERED_DATE VARCHAR(255),
ORDER_DATE VARCHAR(255),
CART_ID NUMERIC(19,0),
EMP_ID NUMERIC(19,0), 
PRIMARY KEY ( ID ),
CONSTRAINT  EMPLOYEE_ROLE_FK1  FOREIGN KEY ( CART_ID ) REFERENCES  CART  ( CART_ID ) , 
CONSTRAINT  EMPLOYEE_ROLE_FK2  FOREIGN KEY ( EMP_ID ) REFERENCES  EMPLOYEE  ( EMP_ID ) 
);

   CREATE SEQUENCE  CART_SEQUENCE   
	MINVALUE 1 
	MAXVALUE 999999999999 
	INCREMENT BY 1 
	START WITH 1001 ;


INSERT INTO  EMPLOYEE  VALUES ('2', 'mahmut', '$2a$10$Ojm9B05Bt3uyX1.la7d80.JOteZQ7IUUNuiGpF4UNA//bAuJaCcbC', 'tuncer', 'mahmutt');
INSERT INTO  EMPLOYEE  VALUES ('3', 'cem', '$2a$10$Ojm9B05Bt3uyX1.la7d80.JOteZQ7IUUNuiGpF4UNA//bAuJaCcbC', 'yılmaz', 'cemyılmaz');


INSERT INTO  EMPLOYEE_ROLE  VALUES ('2', '1', '1', TO_TIMESTAMP('2019-09-19 19:46:31.000000000', 'YYYY-MM-DD HH24:MI:SS.FF'));
INSERT INTO  EMPLOYEE_ROLE  VALUES ('3', '1', '1', TO_TIMESTAMP('2019-09-19 19:46:31.000000000', 'YYYY-MM-DD HH24:MI:SS.FF'));
